import { Job, User, Conversation } from './types';

export const MOCK_WORKERS: User[] = [
  {
    id: 'w1',
    name: 'Peter Mukasa',
    phone: '+256712000001',
    role: 'worker',
    location: 'Nakawa, Kampala',
    rating: 4.8,
    completedJobs: 42,
    skills: ['Cleaner', 'Builder', 'Mover'],
    about:
      'I am a dedicated professional with over 5 years of experience in house cleaning and small-scale construction. I pride myself on punctuality and quality work for all my clients in the Kampala area.',
    responseTime: '< 15 mins',
    lastActive: '2 hours ago',
    isVerified: true,
  },
  {
    id: 'w2',
    name: 'Brian Okello',
    phone: '+256701000002',
    role: 'worker',
    location: 'Kololo, Kampala',
    rating: 4.9,
    completedJobs: 124,
    skills: ['Electrician', 'Plumber'],
    about:
      'Licensed electrician with 8 years of experience. Available for emergency calls 24/7. I carry all necessary tools.',
    responseTime: '< 5 mins',
    lastActive: '30 mins ago',
    isVerified: true,
  },
  {
    id: 'w3',
    name: 'Sarah Namutebi',
    phone: '+256772000003',
    role: 'worker',
    location: 'Ntinda, Kampala',
    rating: 4.8,
    completedJobs: 89,
    skills: ['Tailor', 'Cleaner'],
    about: 'Expert tailor and house cleaner. Fast, reliable, and detail-oriented. Five-star service guaranteed.',
    responseTime: '< 20 mins',
    lastActive: '1 hour ago',
    isVerified: true,
  },
  {
    id: 'w4',
    name: 'Ivan Kato',
    phone: '+256782000004',
    role: 'worker',
    location: 'Kiwatule, Kampala',
    rating: 4.6,
    completedJobs: 24,
    skills: ['Mover', 'Gardener', 'Cleaner'],
    about: 'Strong and reliable. Available for heavy lifting, moving, and garden work. Own transport available.',
    responseTime: '< 30 mins',
    lastActive: '3 hours ago',
    isVerified: false,
  },
  {
    id: 'w5',
    name: 'Grace Ateenyi',
    phone: '+256752000005',
    role: 'worker',
    location: 'Entebbe',
    rating: 4.7,
    completedJobs: 38,
    skills: ['Cook', 'Cleaner', 'Baker'],
    about:
      'Professional cook with catering experience for events and households. Specializes in Ugandan and international cuisine.',
    responseTime: '< 15 mins',
    lastActive: '5 hours ago',
    isVerified: true,
  },
  {
    id: 'w6',
    name: 'Joseph Kalungi',
    phone: '+256752000006',
    role: 'worker',
    location: 'Kampala, UG',
    rating: 4.5,
    completedJobs: 15,
    skills: ['Builder', 'Painter'],
    about: 'Experienced builder and painter with 3 years in construction. Available weekdays and weekends.',
    responseTime: '< 1 hr',
    lastActive: '6 hours ago',
    isVerified: false,
  },
];

export const MOCK_EMPLOYERS: User[] = [
  {
    id: 'e1',
    name: 'Mukasa John',
    phone: '+256712100001',
    role: 'employer',
    location: 'Kampala, Uganda',
    isVerified: true,
  },
  {
    id: 'e2',
    name: 'Sarah Namukasa',
    phone: '+256772100002',
    role: 'employer',
    location: 'Kololo, Kampala',
    isVerified: true,
  },
  {
    id: 'e3',
    name: 'Grace M.',
    phone: '+256782100003',
    role: 'employer',
    location: 'Nakawa, Kampala',
    isVerified: false,
  },
  {
    id: 'e4',
    name: 'Events by Grace',
    phone: '+256701100004',
    role: 'employer',
    location: 'Munyonyo, Kampala',
    isVerified: true,
  },
  {
    id: 'e5',
    name: 'TechStart Uganda',
    phone: '+256752100005',
    role: 'employer',
    location: 'CBD, Kampala',
    isVerified: true,
  },
  {
    id: 'e6',
    name: 'Sarah Namuli',
    phone: '+256772100006',
    role: 'employer',
    location: 'Entebbe, UG',
    isVerified: false,
  },
];

const now = new Date();
const tomorrow = new Date(now.getTime() + 86400000);
const in3Days = new Date(now.getTime() + 3 * 86400000);
const in5Days = new Date(now.getTime() + 5 * 86400000);

export const MOCK_JOBS: Job[] = [
  {
    id: 'j1',
    title: 'Need 3 movers in Kampala',
    description:
      'We are moving furniture from a 3-bedroom house in Kiwatule to Ntinda. Need strong workers who can handle heavy items. Truck will be provided. Job starts at 10 AM.',
    location: 'Kiwatule, Kampala',
    dateTime: now.toISOString(),
    workersNeeded: 3,
    pay: 20000,
    urgency: 'immediate',
    status: 'open',
    employerId: 'e1',
    employerName: 'Mukasa John',
    employerPhone: '+256712100001',
    applicants: [],
    skills: ['Mover', 'Heavy Lifting'],
    estimatedHours: 4,
    distanceKm: 1.2,
    createdAt: now.toISOString(),
  },
  {
    id: 'j2',
    title: 'Experienced Plumber for Sink Repair',
    description:
      'A kitchen pipe has burst causing significant leakage. Need an experienced plumber to arrive within 2 hours to replace the section and seal the leak. Tools are not provided; please bring your own plumbing kit.',
    location: 'Kololo, Kampala',
    dateTime: tomorrow.toISOString(),
    workersNeeded: 1,
    pay: 45000,
    urgency: 'scheduled',
    status: 'open',
    employerId: 'e2',
    employerName: 'Sarah Namukasa',
    employerPhone: '+256772100002',
    applicants: [
      {
        workerId: 'w1',
        workerName: 'Peter Mukasa',
        rating: 4.8,
        completedJobs: 42,
        skills: ['Cleaner', 'Builder', 'Mover'],
        appliedAt: new Date(now.getTime() - 3600000).toISOString(),
        status: 'pending',
      },
    ],
    skills: ['Plumbing', 'Emergency', 'Tools Required'],
    estimatedHours: 3,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    distanceKm: 3.5,
    createdAt: new Date(now.getTime() - 7200000).toISOString(),
  },
  {
    id: 'j3',
    title: 'Gardener for Compound Cleaning',
    description:
      'Need a gardener to trim hedges, mow lawn, and clean the compound. Tools will be provided. Compound is medium-sized. Should be done before noon.',
    location: 'Ntinda, Kampala',
    dateTime: now.toISOString(),
    workersNeeded: 1,
    pay: 15000,
    urgency: 'immediate',
    status: 'open',
    employerId: 'e1',
    employerName: 'Mukasa John',
    employerPhone: '+256712100001',
    applicants: [],
    skills: ['Gardening', 'Cleaning'],
    estimatedHours: 3,
    distanceKm: 0.8,
    createdAt: new Date(now.getTime() - 1800000).toISOString(),
  },
  {
    id: 'j4',
    title: 'Emergency Pipe Repair',
    description:
      'A kitchen pipe has burst causing significant leakage. Need an experienced plumber to arrive within 2 hours to replace the section and seal the leak. Tools are not provided; please bring your own plumbing kit.',
    location: 'Kireka, Kampala',
    dateTime: now.toISOString(),
    workersNeeded: 1,
    pay: 85000,
    urgency: 'immediate',
    status: 'in_progress',
    employerId: 'e2',
    employerName: 'Sarah Namukasa',
    employerPhone: '+256772100002',
    applicants: [
      {
        workerId: 'w2',
        workerName: 'Brian Okello',
        rating: 4.9,
        completedJobs: 124,
        skills: ['Electrician', 'Plumber'],
        appliedAt: new Date(now.getTime() - 1800000).toISOString(),
        status: 'accepted',
      },
      {
        workerId: 'w1',
        workerName: 'Peter Mukasa',
        rating: 4.8,
        completedJobs: 42,
        skills: ['Cleaner', 'Builder', 'Mover'],
        appliedAt: new Date(now.getTime() - 3600000).toISOString(),
        status: 'pending',
      },
    ],
    skills: ['Plumbing', 'Emergency'],
    estimatedHours: 2,
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&q=80',
    distanceKm: 2.1,
    createdAt: new Date(now.getTime() - 5400000).toISOString(),
  },
  {
    id: 'j5',
    title: 'Bulk Delivery (Grocery)',
    description:
      'Need 2 people to help with grocery delivery across Nakawa market area. Must have a motorcycle or be willing to use our vehicle. Long hours but good pay.',
    location: 'Nakawa Market',
    dateTime: in3Days.toISOString(),
    workersNeeded: 2,
    pay: 30000,
    urgency: 'scheduled',
    status: 'open',
    employerId: 'e3',
    employerName: 'Grace M.',
    employerPhone: '+256782100003',
    applicants: [],
    skills: ['Delivery', 'Driving'],
    estimatedHours: 6,
    distanceKm: 4.2,
    createdAt: new Date(now.getTime() - 10800000).toISOString(),
  },
  {
    id: 'j6',
    title: 'House Painting - 3 Rooms',
    description:
      'Need 2 experienced painters for a 3-room house in Ntinda. Paint and tools will be provided. Estimate 2 days of work. Professional finish required.',
    location: 'Ntinda, Kampala',
    dateTime: in3Days.toISOString(),
    workersNeeded: 2,
    pay: 150000,
    urgency: 'scheduled',
    status: 'open',
    employerId: 'e1',
    employerName: 'Mukasa John',
    employerPhone: '+256712100001',
    applicants: [
      {
        workerId: 'w6',
        workerName: 'Joseph Kalungi',
        rating: 4.5,
        completedJobs: 15,
        skills: ['Builder', 'Painter'],
        appliedAt: new Date(now.getTime() - 7200000).toISOString(),
        status: 'pending',
      },
    ],
    skills: ['Painting', 'Renovation'],
    estimatedHours: 16,
    distanceKm: 5.0,
    createdAt: new Date(now.getTime() - 14400000).toISOString(),
  },
  {
    id: 'j7',
    title: 'Event Setup - Wedding Reception',
    description:
      'Need 5 helpers for wedding reception setup at Munyonyo. Chairs, tables, and decorations need to be arranged. Event starts at 2 PM, setup from 8 AM.',
    location: 'Munyonyo, Kampala',
    dateTime: in5Days.toISOString(),
    workersNeeded: 5,
    pay: 25000,
    urgency: 'scheduled',
    status: 'open',
    employerId: 'e4',
    employerName: 'Events by Grace',
    employerPhone: '+256701100004',
    applicants: [],
    skills: ['Events', 'Setup'],
    estimatedHours: 8,
    distanceKm: 7.3,
    createdAt: new Date(now.getTime() - 21600000).toISOString(),
  },
  {
    id: 'j8',
    title: 'Electrician for Office Wiring',
    description:
      'New office in Kampala CBD needs electrical wiring for 10 workstations. Must be certified and experienced. All materials provided.',
    location: 'Kampala CBD',
    dateTime: tomorrow.toISOString(),
    workersNeeded: 1,
    pay: 200000,
    urgency: 'scheduled',
    status: 'open',
    employerId: 'e5',
    employerName: 'TechStart Uganda',
    employerPhone: '+256752100005',
    applicants: [],
    skills: ['Electrical', 'Certified'],
    estimatedHours: 8,
    distanceKm: 2.8,
    createdAt: new Date(now.getTime() - 28800000).toISOString(),
  },
  {
    id: 'j9',
    title: 'Laundry & Ironing (4 bags)',
    description:
      'Large family needs laundry washed, dried, and ironed. About 4 big bags of clothes. Machine available on site.',
    location: 'Naguru, Kampala',
    dateTime: now.toISOString(),
    workersNeeded: 1,
    pay: 20000,
    urgency: 'immediate',
    status: 'in_progress',
    employerId: 'e3',
    employerName: 'Grace M.',
    employerPhone: '+256782100003',
    applicants: [
      {
        workerId: 'w3',
        workerName: 'Sarah Namutebi',
        rating: 4.8,
        completedJobs: 89,
        skills: ['Tailor', 'Cleaner'],
        appliedAt: new Date(now.getTime() - 3600000).toISOString(),
        status: 'accepted',
      },
    ],
    skills: ['Laundry', 'Ironing'],
    estimatedHours: 4,
    distanceKm: 3.1,
    createdAt: new Date(now.getTime() - 18000000).toISOString(),
  },
  {
    id: 'j10',
    title: 'Compound Security Guard (Night)',
    description:
      'Need a trustworthy security guard for one night, 8 PM to 6 AM. Event happening at residence in Kololo. Must be sober and alert.',
    location: 'Kololo, Kampala',
    dateTime: tomorrow.toISOString(),
    workersNeeded: 1,
    pay: 35000,
    urgency: 'scheduled',
    status: 'open',
    employerId: 'e2',
    employerName: 'Sarah Namukasa',
    employerPhone: '+256772100002',
    applicants: [],
    skills: ['Security', 'Night Shift'],
    estimatedHours: 10,
    distanceKm: 3.5,
    createdAt: new Date(now.getTime() - 36000000).toISOString(),
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv1',
    otherUserId: 'w2',
    otherUserName: 'Brian Okello',
    lastMessage: 'I will be there by 9 AM sharp.',
    lastMessageTime: '2 min ago',
    unread: 2,
    jobTitle: 'Emergency Pipe Repair',
    jobId: 'j4',
    messages: [
      {
        id: 'm1',
        fromId: 'current',
        toId: 'w2',
        fromName: 'You',
        text: 'Hi Brian, your application has been accepted for the pipe repair job.',
        timestamp: new Date(now.getTime() - 3600000).toISOString(),
        read: true,
      },
      {
        id: 'm2',
        fromId: 'w2',
        toId: 'current',
        fromName: 'Brian Okello',
        text: 'Thank you! I will be there by 9 AM sharp.',
        timestamp: new Date(now.getTime() - 120000).toISOString(),
        read: false,
      },
    ],
  },
  {
    id: 'conv2',
    otherUserId: 'e1',
    otherUserName: 'Mukasa John',
    lastMessage: 'Job confirmed. See you tomorrow at 8 AM.',
    lastMessageTime: '1 hr ago',
    unread: 0,
    jobTitle: 'House Painting - 3 Rooms',
    jobId: 'j6',
    messages: [
      {
        id: 'm3',
        fromId: 'e1',
        toId: 'current',
        fromName: 'Mukasa John',
        text: 'Job confirmed. See you tomorrow at 8 AM.',
        timestamp: new Date(now.getTime() - 3600000).toISOString(),
        read: true,
      },
    ],
  },
  {
    id: 'conv3',
    otherUserId: 'w3',
    otherUserName: 'Sarah Namutebi',
    lastMessage: 'Can you bring your own cleaning supplies?',
    lastMessageTime: '3 hrs ago',
    unread: 1,
    jobTitle: 'House Cleaning',
    messages: [
      {
        id: 'm4',
        fromId: 'w3',
        toId: 'current',
        fromName: 'Sarah Namutebi',
        text: 'Can you bring your own cleaning supplies?',
        timestamp: new Date(now.getTime() - 10800000).toISOString(),
        read: false,
      },
    ],
  },
];
